# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sandbase < Formula
  desc "SandBase AI platform CLI"
  homepage "https://sandbase.ai"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sandbaseai/cli/releases/download/v0.1.1/sandbase_0.1.1_darwin_amd64.tar.gz"
      sha256 "53712d0ca471b721c0939d1983f964f08487104b621b4bba12d74fa808f4937b"

      define_method(:install) do
        bin.install "sandbase"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sandbaseai/cli/releases/download/v0.1.1/sandbase_0.1.1_darwin_arm64.tar.gz"
      sha256 "feffeed5f6deed79b4f37d767da9a83e9e2edf065b32b91ecd312992b1799cc1"

      define_method(:install) do
        bin.install "sandbase"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandbaseai/cli/releases/download/v0.1.1/sandbase_0.1.1_linux_amd64.tar.gz"
      sha256 "4c5c6d007dbfafbe9015e49723db55814954f1c6983697e36178babb1b7efe0e"
      define_method(:install) do
        bin.install "sandbase"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandbaseai/cli/releases/download/v0.1.1/sandbase_0.1.1_linux_arm64.tar.gz"
      sha256 "db77f968436ad9d9fe75bdb36d4579838186ab281601319cabaef187ea45b31b"
      define_method(:install) do
        bin.install "sandbase"
      end
    end
  end
end
