# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sandbase < Formula
  desc "SandBase AI platform CLI"
  homepage "https://sandbase.ai"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sandbaseai/cli/releases/download/v0.2.2/sandbase_0.2.2_darwin_amd64.tar.gz"
      sha256 "ba9fe535c3e328550f8123e6f9d345dea297a07505cb9dfeff9bac1442462917"

      define_method(:install) do
        bin.install "sandbase"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sandbaseai/cli/releases/download/v0.2.2/sandbase_0.2.2_darwin_arm64.tar.gz"
      sha256 "4bdb603ce6ba8b642aea5dd79e12519b07972085356608368f5f0ca7ce583fd2"

      define_method(:install) do
        bin.install "sandbase"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandbaseai/cli/releases/download/v0.2.2/sandbase_0.2.2_linux_amd64.tar.gz"
      sha256 "eefae3b757a832a35c14c4043de7938f4b7170f4aefd9d0bc9b8a6608582ae35"
      define_method(:install) do
        bin.install "sandbase"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandbaseai/cli/releases/download/v0.2.2/sandbase_0.2.2_linux_arm64.tar.gz"
      sha256 "8198a6703ee35765847183ff8dad7b31dde4f9dabf9d215b11c6dd1448620f51"
      define_method(:install) do
        bin.install "sandbase"
      end
    end
  end
end
