# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Sandbase < Formula
  desc "SandBase AI platform CLI"
  homepage "https://sandbase.ai"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/sandbaseai/cli/releases/download/v0.2.1/sandbase_0.2.1_darwin_amd64.tar.gz"
      sha256 "1acd369f09fcc11c89db3213b8d8a75ad707caffa12ca6ffd6b688386e38c3c4"

      define_method(:install) do
        bin.install "sandbase"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/sandbaseai/cli/releases/download/v0.2.1/sandbase_0.2.1_darwin_arm64.tar.gz"
      sha256 "3510ad46eee3c8c9cca182e111a05384c163fbde8acdcb3989cf7be323fce949"

      define_method(:install) do
        bin.install "sandbase"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandbaseai/cli/releases/download/v0.2.1/sandbase_0.2.1_linux_amd64.tar.gz"
      sha256 "d2e961a6c97c7e301f29f39833cd688c9c1b1c9d0e9513218fa5e2a210aefd84"
      define_method(:install) do
        bin.install "sandbase"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/sandbaseai/cli/releases/download/v0.2.1/sandbase_0.2.1_linux_arm64.tar.gz"
      sha256 "92c1eabe6fc3aad00fbe3fd1cd429f86da534ad3787e5bf19b653d21f0e65e89"
      define_method(:install) do
        bin.install "sandbase"
      end
    end
  end
end
